language: node_js
node_js:
- '4.2.3'
sudo: false
cache:
  directories:
  - node_modules
env:
- APPLICATION_URI="http:\/\/example.com"
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
